### PR TITLE
fix(manager): remove final modifier for the method get repository

### LINKED ISSUE #142: cannot mock the final protected function getRepository()
Hi

I want to write unit test for a method in my manager that extends the `BaseEntityManager`
I use `getRepository` to make a query then I have some business logic for a result which is get from the query, before the result is returned.

I just want to test my business logic so I mock the `getRepository()` (because the returned result from the query does not matter for me in that case)
But the php unit is not able to do that because of the `final` modifier

Can we remove the that `final` modifier ?

### PR DESCRIPTION
**Pull request by phucwan91**
## Subject
cannot mock a final method for testing

Closes #142 

## Changelog

```markdown
### Changed
- Remove the final modifier for the `getRepository` method
```

### To do
- [x] removed the final modifier
- [x] updated tests for the base entity manager

### CODE REVIEW

File: tests/Entity/BaseEntityManagerTest.php [hunk 1]
```diff
@@ -16,74 +16,99 @@
...
-{
-    public function getRepositoryFromBaseClass(): EntityRepository
-    {
-        return $this->getRepository();
-    }
-}
-
+/**
+ * Class BaseEntityManagerTest.
+ */
```
Comment (greg0ire) [inline tests/Entity/BaseEntityManagerTest.php]: Please remove this comment

File: tests/Entity/BaseEntityManagerTest.php [hunk 2]
```diff
@@ -16,74 +16,99 @@
...
-        return new EntityManager('classname', $registry);
+        $this->registry = $this->createMock(ManagerRegistry::class);
+        $this->objectManager = $this->createMock(ObjectManager::class);
+        $this->manager = $this->getMockForAbstractClass(BaseEntityManager::class, ['classname', $this->registry]);
     }
 
-    public function test()
+    /**
+     * Test get class name.
+     */
```
Comment (greg0ire) [inline tests/Entity/BaseEntityManagerTest.php]: If you think the method name is bad, feel free to change it but please don't add this comment. Same for the methods below please.

File: tests/Entity/BaseEntityManagerTest.php [hunk 3]
```diff
@@ -16,74 +16,99 @@
...
+        $this->registry->expects($this->once())->method('getManagerForClass')->willReturn($this->objectManager);
+
+        $r = new \ReflectionObject($this->manager);
+        $m = $r->getMethod('getRepository');
+        $m->setAccessible(true);
 
-        $manager = new EntityManager('classname', $registry);
-        $repository = $manager->getRepositoryFromBaseClass();
-        $this->assertInstanceOf(EntityRepository::class, $repository);
+        $this->assertInstanceOf(EntityRepository::class, $m->invoke($this->manager));
```
Comment (greg0ire) [inline tests/Entity/BaseEntityManagerTest.php]: Why do we have to change all this test exactly? I don't see how this relates to your code change…

Comment (greg0ire) [reply tests/Entity/BaseEntityManagerTest.php]: Ok I think I get it now, you're using reflection because of `getMockForAbstracClass()`, allowing you to call the actual code. I guess that's fine.

**Comment by greg0ire** [comment]
Please edit your initial message to add a changelog (it will be included in the release).

The format is a bit special, see http://keepachangelog.com

**Comment by cbastienbaron** [comment]
Hey,

it is plannified to tag this hot fix on packagist plz ?

**Comment by greg0ire** [comment]
Expect a release tonight.

**Comment by cbastienbaron** [comment]
u rocks dude ! :tada:
